config/routes.rb
Rails.application.routes.draw do
  root to: 'places#index'

  get :status, to: 'application#status'
  resources :places
  resources :states, only: [:index]
  resources :shops, only: [:create, :destroy]
end

app/models/opening_hour.rb
class OpeningHour < ActiveRecord::Base
  validates :week_day, :open, :close, presence: true

  default_scope -> { order(:week_day) }

  def serializable_hash(*)
    {
      'week_day' => week_day,
      'open' => open.strftime('%H:%M'),
      'close' => close.strftime('%H:%M'),
    }
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
  validates :name, :address_line_1, :city, :postal_code, :categories, :state_id,
            :shop_id, presence: true
  belongs_to :shop
  belongs_to :state
  has_many :opening_hours
  accepts_nested_attributes_for :opening_hours

  def build_opening_hours
    existing = opening_hours.map(&:week_day)
    (0..6).reject { |wd| existing.include?(wd) }
          .each { |wd| opening_hours.build(week_day: wd) }
  end

  def opening_hours_attributes=(attrs_hash)
    existing = opening_hours.index_by { |oh| oh.week_day.to_s }
    vals = attrs_hash.values.map!(&:stringify_keys)
    vals.each do |attrs|
      has_key = existing.key?(attrs['week_day'])
      is_blank = attrs.values_at('open', 'close').all?(&:blank?)

      if is_blank
        existing[attrs['week_day']].mark_for_destruction if has_key
      elsif has_key
        existing[attrs['week_day']].assign_attributes(attrs)
      else
        opening_hours.build(attrs)
      end
    end
  end

  def serializable_hash(*)
    hash = attributes.symbolize_keys
      .slice(:id, :name, :address_line_1, :address_line_2, :alt_phone,
             :categories, :city, :description, :district, :email, :fax, :marker_url,
             :home_page, :images, :lat, :lon, :main_phone, :mobile_phone, :name,
              :videos, :only_cash, :postal_code)
      .merge(state: state.uf)
      .merge(opening_hours: opening_hours)
  end

  def self.select_for_serialization
    includes(:state, :opening_hours)
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :places
  validates :name, presence: true
  before_create { self.token = SecureRandom.hex }
end

app/models/state.rb
class State < ActiveRecord::Base
  def self.uf!(uf)
    self.find_by!(uf: uf.to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def status
    render text: 'OK'
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_filter :authenticate
  respond_to :json, :html, :js

  def index
    if @shop
      places = @shop.places
      if params[:o].present?
        params[:o] = params[:o].sub("state", "state_id")
        places = places.order(params[:o])
      end
    end

    respond_to do |format|
      format.html { @shops = Shop.all }
      format.js { render(json: places.select_for_serialization, callback: params[:callback]) }
      format.json { respond_with(places.select_for_serialization) }
    end
  end

  def show
    respond_with(Place.find(params[:id]))
  end

  def new
    @place = Place.new
  end

  def edit
    @place = Place.find(params[:id])
  end

  def create
    @place = Place.new(place_params)

    if @place.save
      respond_to do |format|
        format.html { redirect_to edit_place_path(@place), notice: 'Place was successfully created.' }
        format.json { respond_with(@place) }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { respond_with(@place) }
      end
    end
  end

  def update
    @place = Place.find(params[:id])
    if @place.update(place_params)
      respond_to do |format|
        format.html {redirect_to edit_place_path(@place), notice: 'Place was successfully updated.' }
        format.json { respond_with(@place) }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { respond_with(@place) }
      end
    end
  end

  def destroy
    place = Place.find(params[:id])
    place.destroy!

    respond_to do |format|
        format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
        format.json { respond_with(place) }
      end
  end

  private

  # Only allow a trusted parameter "white list" through.
  def place_params
    ps = params.require(:place).permit(:name, :state_id, :address_line_1,
      :address_line_2, :city, :district, :postal_code, :main_phone, :alt_phone,
      :mobile_phone, :fax, :home_page, :lat, :lon, :description, :email, :marker_url,
      :shop_id, :only_cash, images: [], categories: [], videos: [],
      opening_hours_attributes: [:week_day, :open, :close])
    ps.fetch(:images, []).reject!(&:blank?)
    ps.fetch(:categories, []).reject!(&:blank?)

    if params[:place][:shop_host].present?
      ps.merge!(shop_id: Shop.find_by!(host: params[:place][:shop_host]).id)
      ps.delete(:shop_host)
    end

    ps
  end

  private

  def authenticate
    return true if @shop = Shop.find_by(host: (env['HTTP_X_STORE'] || "unknown-host").split(':').first)

    if params[:format] == 'js'
      @shop = Shop.find_by!(token: params[:token])
    else
      authenticate_or_request_with_http_basic { |u, p| u == ENV['HTTP_USER'] && p == ENV['HTTP_PASSWORD'] }
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to places_path
    else
      redirect_to :back
    end
  end

  def destroy
    Shop.find(params[:id]).destroy!
    redirect_to places_path
  end

  def shop_params
    params.require(:shop).permit(:name, :host)
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  respond_to :json

  def index
    respond_with(State.all)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_field(f, method, *args, &blk)
    label = f.label(method)
    field = if block_given?
        capture { blk.call(method) }
      else
        f.text_field method, *args
      end
    content_tag :div, label + content_tag(:div, field, class: 'control'), class: 'field'
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Places</title>
  <%= stylesheet_link_tag 'scaffold.css', media: 'all' %>
  <%= javascript_include_tag '//code.jquery.com/jquery-2.1.1.min.js',
                             'jquery_ujs.js' %>

  <%= csrf_meta_tags %>
  <style>
    body { width: 940px; margin: 0 auto; }
    td, th { padding: 5px; }
    td:first-child, th:first-child { padding-left: 0; }
    th { text-align: left }
    .control input[type=text],
    .control select {
      display: block;
      width: 350px;
      font-size: 14px;
      line-height: 20px;
    }
    .control input[type=checkbox] { height: 24px; }
    label {
      display: inline-block;
      width: 200px;
      text-align: right;
      padding-right: 20px;
      line-height: 30px;
      vertical-align: top;
    }
    .control { display: inline-block; }
  </style>
</head>
<body>

<p id="notice"><%= notice %></p>
<%= yield %>

<script>
var buttons = document.querySelectorAll('[data-add]');
for (var i =0 ; i < buttons.length; i++) {
  buttons[i].onclick = function () {
    var input = document.createElement('div');
    input.innerHTML = this.dataset.add;
    this.parentElement.insertBefore(input, this);
  }
}
</script>
</body>
</html>

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_field f, :shop_id do |m| %>
    <%= f.select m, Shop.pluck(:name, :id), prompt: true %>
  <% end %>
  <%= form_field f, :name %>
  <%= form_field f, :state_id do |m| %>
    <%= f.select m, State.pluck(:name, :id), prompt: true %>
  <% end %>
  <%= form_field f, :address_line_1 %>
  <%= form_field f, :address_line_2 %>
  <%= form_field f, :city %>
  <%= form_field f, :district %>
  <%= form_field f, :postal_code %>
  <%= form_field f, :main_phone %>
  <%= form_field f, :alt_phone %>
  <%= form_field f, :mobile_phone %>
  <%= form_field f, :fax %>
  <%= form_field f, :home_page %>
  <%= form_field f, :lat %>
  <%= form_field f, :lon %>
  <%= form_field f, :description %>
  <%= form_field f, :email %>
  <%= form_field f, :marker_url %>
  <%= form_field f, :only_cash do |m| %><%= f.check_box m %><% end %>
  <%= form_field f, :categories do |m| %>
    <% (@place.send(m) || []).each do |i| %>
      <%= text_field_tag "place[#{m}][]", i %>
    <% end %>
    <%= tag :input, type: :button, value: ?+, data: { add: text_field_tag("place[#{m}][]").to_str } %>
  <% end %>
  <%= form_field f, :images do |m| %>
    <% (@place.send(m) || []).each do |i| %>
      <%= text_field_tag "place[#{m}][]", i %>
    <% end %>
    <%= tag :input, type: :button, value: ?+, data: { add: text_field_tag("place[#{m}][]").to_str } %>
  <% end %>
  <%= form_field f, :videos do |m| %>
    <% (@place.send(m) || []).each do |i| %>
      <%= text_field_tag "place[#{m}][]", i %>
    <% end %>
    <%= tag :input, type: :button, value: ?+, data: { add: text_field_tag("place[#{m}][]").to_str } %>
  <% end %>
  <div class="field">
    <%= f.label :opening_hours %>
    <div class="control">
      <table>
        <% @place.build_opening_hours %>
        <%= f.fields_for :opening_hours, @place.opening_hours.sort_by(&:week_day) do |fo| %>
          <tr>
            <td>
              <%= fo.hidden_field :week_day %>
              <%= I18n.t(:'date.day_names')[fo.object.week_day] %>
            </td>
            <td><%= fo.text_field :open, placeholder: 'HH:MM', style: 'width: 100px;',
                                  value: fo.object.open.try(:strftime, '%H:%M') %></td>
            <td><%= fo.text_field :close, placeholder: 'HH:MM', style: 'width: 100px;',
                                  value: fo.object.close.try(:strftime, '%H:%M') %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<% @shops.each do |shop| %>
  <h3>
    <%= shop.name %> (<%= shop.token %>) Host: <%= shop.host %>
    <small><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></small>
  </h3>
  <table>
    <tbody>
      <% shop.places.each do |place| %>
        <tr>
          <td><%= place.name %></td>
          <td><%= place.city %></td>
          <td><%= place.state.name %></td>
          <td><%= link_to 'Edit', edit_place_path(place) %></td>
          <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<hr />

<%= form_for Shop.new do |f| %>
  <%= link_to 'New Place', new_place_path %> |
  <%= f.text_field :name, placeholder: 'New Shop' %>
  <%= f.text_field :host, placeholder: 'Shop' %>
  <%= f.submit %>
<% end %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>